decode binary string to ascii for citation export
before this change scholar.py would throw an error

```
TypeError: can't concat bytes to str
```

This is fixed simply by converting the binary string to ascii.

Also, the newline is no longer necessary.